#!/usr/bin/env bash

PLAYER_HP_MAX=5
PLAYER_SPEED=2
PLAYER_FIRE_COOLDOWN=2
PLAYER_MOVE_HOLD_FRAMES=5
PLAYER_FIRE_HOLD_FRAMES=6

ENEMY_BULLET_DELAY_BASE=28
ENEMY_BULLET_SPEED_DELAY=2

FRAME_DELAY=0.045
STAR_COUNT=42

HUD_LINES=3
MIN_WIDTH=40
MIN_HEIGHT=18

DATA_DIR="data"
HIGH_SCORE_FILE="$DATA_DIR/highscore.dat"
